//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

using System;
using System.Linq;

using LinqToDB;
using LinqToDB.Mapping;

namespace DataModels
{
	/// <summary>
	/// Database       : MiR
	/// Data Source    : .
	/// Server Version : 14.00.1000
	/// </summary>
	public partial class MiRDB : LinqToDB.Data.DataConnection
	{
		public ITable<ApplicationLog>    ApplicationLogs     { get { return this.GetTable<ApplicationLog>(); } }
		public ITable<CashBook>          CashBooks           { get { return this.GetTable<CashBook>(); } }
		public ITable<Configuration>     Configurations      { get { return this.GetTable<Configuration>(); } }
		public ITable<CurrenciesHistory> CurrenciesHistories { get { return this.GetTable<CurrenciesHistory>(); } }
		public ITable<Currency>          Currencies          { get { return this.GetTable<Currency>(); } }
		public ITable<Document>          Documents           { get { return this.GetTable<Document>(); } }
		public ITable<ECRReceipt>        ECRReceipts         { get { return this.GetTable<ECRReceipt>(); } }
		public ITable<EnfortaTraffic>    EnfortaTraffic      { get { return this.GetTable<EnfortaTraffic>(); } }
		public ITable<Good>              Goods               { get { return this.GetTable<Good>(); } }
		public ITable<GoodsGroup>        GoodsGroups         { get { return this.GetTable<GoodsGroup>(); } }
		public ITable<InternalLog>       InternalLogs        { get { return this.GetTable<InternalLog>(); } }
		public ITable<Lot>               Lots                { get { return this.GetTable<Lot>(); } }
		public ITable<Network>           Networks            { get { return this.GetTable<Network>(); } }
		public ITable<NextAcct>          NextAccts           { get { return this.GetTable<NextAcct>(); } }
		public ITable<Object>            Objects             { get { return this.GetTable<Object>(); } }
		public ITable<ObjectsGroup>      ObjectsGroups       { get { return this.GetTable<ObjectsGroup>(); } }
		public ITable<Operation>         Operations          { get { return this.GetTable<Operation>(); } }
		public ITable<OperationType>     OperationTypes      { get { return this.GetTable<OperationType>(); } }
		public ITable<Partner>           Partners            { get { return this.GetTable<Partner>(); } }
		public ITable<PartnersGroup>     PartnersGroups      { get { return this.GetTable<PartnersGroup>(); } }
		public ITable<Payment>           Payments            { get { return this.GetTable<Payment>(); } }
		public ITable<PaymentType>       PaymentTypes        { get { return this.GetTable<PaymentType>(); } }
		public ITable<PriceRule>         PriceRules          { get { return this.GetTable<PriceRule>(); } }
		public ITable<Registration>      Registrations       { get { return this.GetTable<Registration>(); } }
		public ITable<SecurityEvent>     SecurityEvents      { get { return this.GetTable<SecurityEvent>(); } }
		public ITable<Store>             Stores              { get { return this.GetTable<Store>(); } }
		public ITable<System>            Systems             { get { return this.GetTable<System>(); } }
		public ITable<TrafficEn>         TrafficEns          { get { return this.GetTable<TrafficEn>(); } }
		public ITable<Transformation>    Transformations     { get { return this.GetTable<Transformation>(); } }
		public ITable<User>              Users               { get { return this.GetTable<User>(); } }
		public ITable<UsersGroup>        UsersGroups         { get { return this.GetTable<UsersGroup>(); } }
		public ITable<UsersSecurity>     UsersSecurities     { get { return this.GetTable<UsersSecurity>(); } }
		public ITable<VATGroup>          VATGroups           { get { return this.GetTable<VATGroup>(); } }

		public MiRDB()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public MiRDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();
	}

	[Table(Schema="dbo", Name="ApplicationLog")]
	public partial class ApplicationLog
	{
		[PrimaryKey, Identity] public int       ID            { get; set; } // int
		[Column,     Nullable] public string    Message       { get; set; } // nvarchar(255)
		[Column,     Nullable] public int?      UserID        { get; set; } // int
		[Column,     Nullable] public DateTime? UserRealtime  { get; set; } // datetime
		[Column,     Nullable] public string    MessageSource { get; set; } // nvarchar(50)
	}

	[Table(Schema="dbo", Name="CashBook")]
	public partial class CashBook
	{
		[PrimaryKey, Identity] public int       ID           { get; set; } // int
		[Column,     Nullable] public DateTime? Date         { get; set; } // smalldatetime
		[Column,     Nullable] public string    Desc         { get; set; } // nvarchar(255)
		[Column,     Nullable] public int?      OperType     { get; set; } // int
		[Column,     Nullable] public int?      Sign         { get; set; } // int
		[Column,     Nullable] public double?   Profit       { get; set; } // float
		[Column,     Nullable] public int?      UserID       { get; set; } // int
		[Column,     Nullable] public DateTime? UserRealtime { get; set; } // datetime
		[Column,     Nullable] public int?      ObjectID     { get; set; } // int
	}

	[Table(Schema="dbo", Name="Configuration")]
	public partial class Configuration
	{
		[PrimaryKey, Identity] public int    ID     { get; set; } // int
		[Column,     Nullable] public string Key    { get; set; } // nvarchar(50)
		[Column,     Nullable] public string Value  { get; set; } // nvarchar(50)
		[Column,     Nullable] public int?   UserID { get; set; } // int
	}

	[Table(Schema="dbo", Name="CurrenciesHistory")]
	public partial class CurrenciesHistory
	{
		[PrimaryKey, Identity] public int       ID           { get; set; } // int
		[Column,     Nullable] public int?      CurrencyID   { get; set; } // int
		[Column,     Nullable] public double?   ExchangeRate { get; set; } // float
		[Column,     Nullable] public DateTime? Date         { get; set; } // smalldatetime
		[Column,     Nullable] public int?      UserID       { get; set; } // int
	}

	[Table(Schema="dbo", Name="Currencies")]
	public partial class Currency
	{
		[Column(),           PrimaryKey, Identity] public int     ID             { get; set; } // int
		[Column("Currency"), Nullable            ] public string  CurrencyColumn { get; set; } // nvarchar(3)
		[Column(),           Nullable            ] public string  Description    { get; set; } // nvarchar(255)
		[Column(),           Nullable            ] public double? ExchangeRate   { get; set; } // float
		[Column(),           Nullable            ] public int?    Deleted        { get; set; } // int
	}

	[Table(Schema="dbo", Name="Documents")]
	public partial class Document
	{
		[PrimaryKey, Identity] public int       ID                    { get; set; } // int
		[Column,     Nullable] public int?      Acct                  { get; set; } // int
		[Column,     Nullable] public string    InvoiceNumber         { get; set; } // nvarchar(255)
		[Column,     Nullable] public short?    OperType              { get; set; } // smallint
		[Column,     Nullable] public DateTime? InvoiceDate           { get; set; } // smalldatetime
		[Column,     Nullable] public short?    DocumentType          { get; set; } // smallint
		[Column,     Nullable] public DateTime? ExternalInvoiceDate   { get; set; } // smalldatetime
		[Column,     Nullable] public string    ExternalInvoiceNumber { get; set; } // nvarchar(255)
		[Column,     Nullable] public short?    PaymentType           { get; set; } // smallint
		[Column,     Nullable] public string    Recipient             { get; set; } // nvarchar(255)
		[Column,     Nullable] public string    EGN                   { get; set; } // nvarchar(50)
		[Column,     Nullable] public string    Provider              { get; set; } // nvarchar(255)
		[Column,     Nullable] public DateTime? TaxDate               { get; set; } // smalldatetime
		[Column,     Nullable] public string    Reason                { get; set; } // nvarchar(255)
		[Column,     Nullable] public string    Description           { get; set; } // nvarchar(255)
		[Column,     Nullable] public string    Place                 { get; set; } // nvarchar(255)
	}

	[Table(Schema="dbo", Name="ECRReceipts")]
	public partial class ECRReceipt
	{
		[PrimaryKey, Identity   ] public int       ID           { get; set; } // int
		[Column,     NotNull    ] public int       OperType     { get; set; } // int
		[Column,     NotNull    ] public int       Acct         { get; set; } // int
		[Column,     NotNull    ] public int       ReceiptID    { get; set; } // int
		[Column,        Nullable] public DateTime? ReceiptDate  { get; set; } // datetime
		[Column,     NotNull    ] public int       ReceiptType  { get; set; } // int
		[Column,        Nullable] public string    ECRID        { get; set; } // nvarchar(255)
		[Column,        Nullable] public string    Description  { get; set; } // nvarchar(255)
		[Column,        Nullable] public double?   Total        { get; set; } // float
		[Column,     NotNull    ] public int       UserID       { get; set; } // int
		[Column,        Nullable] public DateTime? UserRealTime { get; set; } // datetime
	}

	[Table(Schema="dbo", Name="EnfortaTraffic")]
	public partial class EnfortaTraffic
	{
		[Column, Nullable] public DateTime? Time  { get; set; } // datetime
		[Column, Nullable] public string    IP    { get; set; } // nvarchar(50)
		[Column, Nullable] public long?     Bytes { get; set; } // bigint
	}

	[Table(Schema="dbo", Name="Goods")]
	public partial class Good
	{
		[PrimaryKey, Identity] public int     ID          { get; set; } // int
		[Column,     Nullable] public string  Code        { get; set; } // nvarchar(255)
		[Column,     Nullable] public string  BarCode1    { get; set; } // nvarchar(255)
		[Column,     Nullable] public string  BarCode2    { get; set; } // nvarchar(255)
		[Column,     Nullable] public string  BarCode3    { get; set; } // nvarchar(255)
		[Column,     Nullable] public string  Catalog1    { get; set; } // nvarchar(255)
		[Column,     Nullable] public string  Catalog2    { get; set; } // nvarchar(255)
		[Column,     Nullable] public string  Catalog3    { get; set; } // nvarchar(255)
		[Column,     Nullable] public string  Name        { get; set; } // nvarchar(255)
		[Column,     Nullable] public string  Name2       { get; set; } // nvarchar(255)
		[Column,     Nullable] public string  Measure1    { get; set; } // nvarchar(255)
		[Column,     Nullable] public string  Measure2    { get; set; } // nvarchar(255)
		[Column,     Nullable] public double? Ratio       { get; set; } // float
		[Column,     Nullable] public double? PriceIn     { get; set; } // float
		[Column,     Nullable] public double? PriceOut1   { get; set; } // float
		[Column,     Nullable] public double? PriceOut2   { get; set; } // float
		[Column,     Nullable] public double? PriceOut3   { get; set; } // float
		[Column,     Nullable] public double? PriceOut4   { get; set; } // float
		[Column,     Nullable] public double? PriceOut5   { get; set; } // float
		[Column,     Nullable] public double? PriceOut6   { get; set; } // float
		[Column,     Nullable] public double? PriceOut7   { get; set; } // float
		[Column,     Nullable] public double? PriceOut8   { get; set; } // float
		[Column,     Nullable] public double? PriceOut9   { get; set; } // float
		[Column,     Nullable] public double? PriceOut10  { get; set; } // float
		[Column,     Nullable] public double? MinQtty     { get; set; } // float
		[Column,     Nullable] public double? NormalQtty  { get; set; } // float
		[Column,     Nullable] public string  Description { get; set; } // nvarchar(255)
		[Column,     Nullable] public int?    Type        { get; set; } // int
		[Column,     Nullable] public int?    IsRecipe    { get; set; } // int
		[Column,     Nullable] public int?    TaxGroup    { get; set; } // int
		[Column,     Nullable] public int?    IsVeryUsed  { get; set; } // int
		[Column,     Nullable] public int?    GroupID     { get; set; } // int
		[Column,     Nullable] public int?    Deleted     { get; set; } // int
	}

	[Table(Schema="dbo", Name="GoodsGroups")]
	public partial class GoodsGroup
	{
		[PrimaryKey, Identity] public int    ID   { get; set; } // int
		[Column,     Nullable] public string Name { get; set; } // nvarchar(255)
		[Column,     Nullable] public string Code { get; set; } // nvarchar(255)
	}

	[Table(Schema="dbo", Name="InternalLog")]
	public partial class InternalLog
	{
		[PrimaryKey, Identity] public int    ID      { get; set; } // int
		[Column,     Nullable] public string Message { get; set; } // nvarchar(3000)
	}

	[Table(Schema="dbo", Name="Lots")]
	public partial class Lot
	{
		[PrimaryKey, Identity] public int       ID             { get; set; } // int
		[Column,     Nullable] public string    SerialNo       { get; set; } // nvarchar(255)
		[Column,     Nullable] public DateTime? EndDate        { get; set; } // smalldatetime
		[Column,     Nullable] public DateTime? ProductionDate { get; set; } // smalldatetime
		[Column,     Nullable] public string    Location       { get; set; } // nvarchar(255)
	}

	[Table(Schema="dbo", Name="Network")]
	public partial class Network
	{
		[PrimaryKey, NotNull] public int Num     { get; set; } // int
		[Column,     NotNull] public int Counter { get; set; } // int
	}

	[Table(Schema="dbo", Name="NextAcct")]
	public partial class NextAcct
	{
		[Column(),           Identity           ] public int    ID             { get; set; } // int
		[Column("NextAcct"), PrimaryKey, NotNull] public string NextAcctColumn { get; set; } // nvarchar(50)
	}

	[Table(Schema="dbo", Name="Objects")]
	public partial class Object
	{
		[PrimaryKey, Identity] public int    ID         { get; set; } // int
		[Column,     Nullable] public string Code       { get; set; } // nvarchar(255)
		[Column,     Nullable] public string Name       { get; set; } // nvarchar(255)
		[Column,     Nullable] public string Name2      { get; set; } // nvarchar(255)
		[Column,     Nullable] public int?   PriceGroup { get; set; } // int
		[Column,     Nullable] public int?   IsVeryUsed { get; set; } // int
		[Column,     Nullable] public int?   GroupID    { get; set; } // int
		[Column,     Nullable] public int?   Deleted    { get; set; } // int
	}

	[Table(Schema="dbo", Name="ObjectsGroups")]
	public partial class ObjectsGroup
	{
		[PrimaryKey, Identity] public int    ID   { get; set; } // int
		[Column,     Nullable] public string Code { get; set; } // nvarchar(255)
		[Column,     Nullable] public string Name { get; set; } // nvarchar(255)
	}

	[Table(Schema="dbo", Name="Operations")]
	public partial class Operation
	{
		[PrimaryKey, Identity] public int       ID           { get; set; } // int
		[Column,     Nullable] public int?      OperType     { get; set; } // int
		[Column,     Nullable] public int?      Acct         { get; set; } // int
		[Column,     Nullable] public int?      GoodID       { get; set; } // int
		[Column,     Nullable] public int?      PartnerID    { get; set; } // int
		[Column,     Nullable] public int?      ObjectID     { get; set; } // int
		[Column,     Nullable] public int?      OperatorID   { get; set; } // int
		[Column,     Nullable] public double?   Qtty         { get; set; } // float
		[Column,     Nullable] public int?      Sign         { get; set; } // int
		[Column,     Nullable] public double?   PriceIn      { get; set; } // float
		[Column,     Nullable] public double?   PriceOut     { get; set; } // float
		[Column,     Nullable] public double?   VATIn        { get; set; } // float
		[Column,     Nullable] public double?   VATOut       { get; set; } // float
		[Column,     Nullable] public double?   Discount     { get; set; } // float
		[Column,     Nullable] public int?      CurrencyID   { get; set; } // int
		[Column,     Nullable] public double?   CurrencyRate { get; set; } // float
		[Column,     Nullable] public DateTime? Date         { get; set; } // smalldatetime
		[Column,     Nullable] public string    Lot          { get; set; } // nvarchar(50)
		[Column,     Nullable] public int?      LotID        { get; set; } // int
		[Column,     Nullable] public string    Note         { get; set; } // nvarchar(255)
		[Column,     Nullable] public int?      SrcDocID     { get; set; } // int
		[Column,     Nullable] public int?      UserID       { get; set; } // int
		[Column,     Nullable] public DateTime? UserRealTime { get; set; } // datetime
	}

	[Table(Schema="dbo", Name="OperationType")]
	public partial class OperationType
	{
		[PrimaryKey, Identity] public int    ID { get; set; } // int
		[Column,     Nullable] public string BG { get; set; } // nvarchar(255)
		[Column,     Nullable] public string EN { get; set; } // nvarchar(255)
		[Column,     Nullable] public string DE { get; set; } // nvarchar(255)
		[Column,     Nullable] public string RU { get; set; } // nvarchar(255)
		[Column,     Nullable] public string TR { get; set; } // nvarchar(255)
		[Column,     Nullable] public string SQ { get; set; } // nvarchar(255)
		[Column,     Nullable] public string SR { get; set; } // nvarchar(255)
		[Column,     Nullable] public string RO { get; set; } // nvarchar(255)
		[Column,     Nullable] public string GR { get; set; } // nvarchar(255)
		[Column,     Nullable] public string EL { get; set; } // nvarchar(255)
		[Column,     Nullable] public string ES { get; set; } // nvarchar(255)
		[Column,     Nullable] public string HY { get; set; } // nvarchar(255)
		[Column,     Nullable] public string KA { get; set; } // nvarchar(255)
		[Column,     Nullable] public string PL { get; set; } // nvarchar(255)
		[Column,     Nullable] public string UK { get; set; } // nvarchar(255)
		[Column,     Nullable] public string ZU { get; set; } // nvarchar(255)
		[Column,     Nullable] public string LV { get; set; } // nvarchar(255)
		[Column,     Nullable] public string FI { get; set; } // nvarchar(255)
		[Column,     Nullable] public string AR { get; set; } // nvarchar(255)
	}

	[Table(Schema="dbo", Name="Partners")]
	public partial class Partner
	{
		[Column(),        PrimaryKey, Identity] public int       ID           { get; set; } // int
		[Column(),        Nullable            ] public string    Code         { get; set; } // nvarchar(255)
		[Column(),        Nullable            ] public string    Company      { get; set; } // nvarchar(255)
		[Column(),        Nullable            ] public string    Company2     { get; set; } // nvarchar(255)
		[Column(),        Nullable            ] public string    MOL          { get; set; } // nvarchar(255)
		[Column(),        Nullable            ] public string    MOL2         { get; set; } // nvarchar(255)
		[Column(),        Nullable            ] public string    City         { get; set; } // nvarchar(255)
		[Column(),        Nullable            ] public string    City2        { get; set; } // nvarchar(255)
		[Column(),        Nullable            ] public string    Address      { get; set; } // nvarchar(255)
		[Column(),        Nullable            ] public string    Address2     { get; set; } // nvarchar(255)
		[Column(),        Nullable            ] public string    Phone        { get; set; } // nvarchar(255)
		[Column(),        Nullable            ] public string    Phone2       { get; set; } // nvarchar(255)
		[Column(),        Nullable            ] public string    Fax          { get; set; } // nvarchar(255)
		[Column("eMail"), Nullable            ] public string    EMail        { get; set; } // nvarchar(255)
		[Column(),        Nullable            ] public string    TaxNo        { get; set; } // nvarchar(255)
		[Column(),        Nullable            ] public string    Bulstat      { get; set; } // nvarchar(255)
		[Column(),        Nullable            ] public string    BankName     { get; set; } // nvarchar(255)
		[Column(),        Nullable            ] public string    BankCode     { get; set; } // nvarchar(255)
		[Column(),        Nullable            ] public string    BankAcct     { get; set; } // nvarchar(255)
		[Column(),        Nullable            ] public string    BankVATName  { get; set; } // nvarchar(255)
		[Column(),        Nullable            ] public string    BankVATCode  { get; set; } // nvarchar(255)
		[Column(),        Nullable            ] public string    BankVATAcct  { get; set; } // nvarchar(255)
		[Column(),        Nullable            ] public int?      PriceGroup   { get; set; } // int
		[Column(),        Nullable            ] public double?   Discount     { get; set; } // float
		[Column(),        Nullable            ] public short?    Type         { get; set; } // smallint
		[Column(),        Nullable            ] public short?    IsVeryUsed   { get; set; } // smallint
		[Column(),        Nullable            ] public int?      UserID       { get; set; } // int
		[Column(),        Nullable            ] public int?      GroupID      { get; set; } // int
		[Column(),        Nullable            ] public DateTime? UserRealTime { get; set; } // datetime
		[Column(),        Nullable            ] public int?      Deleted      { get; set; } // int
		[Column(),        Nullable            ] public string    CardNumber   { get; set; } // nvarchar(255)
		[Column(),        Nullable            ] public string    Note1        { get; set; } // nvarchar(255)
		[Column(),        Nullable            ] public string    Note2        { get; set; } // nvarchar(255)
		[Column(),        Nullable            ] public int?      PaymentDays  { get; set; } // int
		[Column(),        Nullable            ] public DateTime? GoodTill2    { get; set; } // datetime
		[Column(),        Nullable            ] public DateTime? GoodTill     { get; set; } // datetime
		[Column(),        Nullable            ] public int?      SecurityType { get; set; } // int
	}

	[Table(Schema="dbo", Name="PartnersGroups")]
	public partial class PartnersGroup
	{
		[PrimaryKey, Identity] public int    ID   { get; set; } // int
		[Column,     Nullable] public string Code { get; set; } // nvarchar(255)
		[Column,     Nullable] public string Name { get; set; } // nvarchar(255)
	}

	[Table(Schema="dbo", Name="Payments")]
	public partial class Payment
	{
		[PrimaryKey, Identity] public int       ID                { get; set; } // int
		[Column,     Nullable] public int?      Acct              { get; set; } // int
		[Column,     Nullable] public int?      OperType          { get; set; } // int
		[Column,     Nullable] public int?      PartnerID         { get; set; } // int
		[Column,     Nullable] public double?   Qtty              { get; set; } // float
		[Column,     Nullable] public int?      Mode              { get; set; } // int
		[Column,     Nullable] public int?      Sign              { get; set; } // int
		[Column,     Nullable] public DateTime? Date              { get; set; } // smalldatetime
		[Column,     Nullable] public int?      UserID            { get; set; } // int
		[Column,     Nullable] public int?      ObjectID          { get; set; } // int
		[Column,     Nullable] public DateTime? UserRealTime      { get; set; } // datetime
		[Column,     Nullable] public int?      Type              { get; set; } // int
		[Column,     Nullable] public string    TransactionNumber { get; set; } // nvarchar(255)
		[Column,     Nullable] public DateTime? EndDate           { get; set; } // smalldatetime
	}

	[Table(Schema="dbo", Name="PaymentTypes")]
	public partial class PaymentType
	{
		[PrimaryKey, Identity] public int    ID            { get; set; } // int
		[Column,     Nullable] public string Name          { get; set; } // nvarchar(255)
		[Column,     Nullable] public int?   PaymentMethod { get; set; } // int
	}

	[Table(Schema="dbo", Name="PriceRules")]
	public partial class PriceRule
	{
		[PrimaryKey, Identity] public int    ID       { get; set; } // int
		[Column,     Nullable] public string Name     { get; set; } // nvarchar(255)
		[Column,     Nullable] public string Formula  { get; set; } // nvarchar(1000)
		[Column,     Nullable] public int?   Enabled  { get; set; } // int
		[Column,     Nullable] public int?   Priority { get; set; } // int
	}

	[Table(Schema="dbo", Name="Registration")]
	public partial class Registration
	{
		[Column(),        PrimaryKey, Identity] public int       ID           { get; set; } // int
		[Column(),        Nullable            ] public string    Code         { get; set; } // nvarchar(255)
		[Column(),        Nullable            ] public string    Company      { get; set; } // nvarchar(255)
		[Column(),        Nullable            ] public string    MOL          { get; set; } // nvarchar(255)
		[Column(),        Nullable            ] public string    City         { get; set; } // nvarchar(255)
		[Column(),        Nullable            ] public string    Address      { get; set; } // nvarchar(255)
		[Column(),        Nullable            ] public string    Phone        { get; set; } // nvarchar(255)
		[Column(),        Nullable            ] public string    Fax          { get; set; } // nvarchar(255)
		[Column("eMail"), Nullable            ] public string    EMail        { get; set; } // nvarchar(255)
		[Column(),        Nullable            ] public string    TaxNo        { get; set; } // nvarchar(255)
		[Column(),        Nullable            ] public string    Bulstat      { get; set; } // nvarchar(255)
		[Column(),        Nullable            ] public string    BankName     { get; set; } // nvarchar(255)
		[Column(),        Nullable            ] public string    BankCode     { get; set; } // nvarchar(255)
		[Column(),        Nullable            ] public string    BankAcct     { get; set; } // nvarchar(255)
		[Column(),        Nullable            ] public string    BankVATAcct  { get; set; } // nvarchar(255)
		[Column(),        Nullable            ] public int?      UserID       { get; set; } // int
		[Column(),        Nullable            ] public DateTime? UserRealTime { get; set; } // datetime
		[Column(),        Nullable            ] public int?      IsDefault    { get; set; } // int
		[Column(),        Nullable            ] public string    Note1        { get; set; } // nvarchar(255)
		[Column(),        Nullable            ] public string    Note2        { get; set; } // nvarchar(255)
		[Column(),        Nullable            ] public int?      Deleted      { get; set; } // int
	}

	[Table(Schema="dbo", Name="SecurityEvents")]
	public partial class SecurityEvent
	{
		[PrimaryKey, Identity   ] public int      ID           { get; set; } // int
		[Column,     NotNull    ] public string   CardNumber   { get; set; } // nvarchar(255)
		[Column,     NotNull    ] public int      Event        { get; set; } // int
		[Column,        Nullable] public string   Comment      { get; set; } // nvarchar(255)
		[Column,        Nullable] public string   ControllerID { get; set; } // nvarchar(50)
		[Column,     NotNull    ] public DateTime Time         { get; set; } // datetime
	}

	[Table(Schema="dbo", Name="Store")]
	public partial class Store
	{
		[PrimaryKey, Identity] public int     ID       { get; set; } // int
		[Column,     Nullable] public int?    ObjectID { get; set; } // int
		[Column,     Nullable] public int?    GoodID   { get; set; } // int
		[Column,     Nullable] public double? Qtty     { get; set; } // float
		[Column,     Nullable] public double? Price    { get; set; } // float
		[Column,     Nullable] public string  Lot      { get; set; } // nvarchar(250)
		[Column,     Nullable] public int?    LotID    { get; set; } // int
		[Column,     Nullable] public int?    LotOrder { get; set; } // int
	}

	[Table(Schema="dbo", Name="System")]
	public partial class System
	{
		[PrimaryKey, NotNull    ] public string    Version    { get; set; } // nvarchar(20)
		[Column,        Nullable] public short?    ProductID  { get; set; } // smallint
		[Column,        Nullable] public DateTime? LastBackup { get; set; } // smalldatetime
	}

	[Table(Schema="dbo", Name="TrafficEn")]
	public partial class TrafficEn
	{
		[Column("datetime"),                   Nullable] public DateTime? Datetime             { get; set; } // datetime
		[Column("src_IP_addr"),                Nullable] public string    SrcIpAddr            { get; set; } // nvarchar(50)
		[Column("src_port"),                   Nullable] public int?      SrcPort              { get; set; } // int
		[Column("input_ifidx\r\ninput_ifidx"), Nullable] public int?      InputIfidxInputIfidx { get; set; } // int
		[Column("dst_IP_addr"),                Nullable] public string    DstIpAddr            { get; set; } // nvarchar(50)
		[Column("dst_port"),                   Nullable] public int?      DstPort              { get; set; } // int
		[Column("output_if_idx"),              Nullable] public int?      OutputIfIdx          { get; set; } // int
		[Column("protocol"),                   Nullable] public string    Protocol             { get; set; } // nvarchar(50)
		[Column("packets"),                    Nullable] public int?      Packets              { get; set; } // int
		[Column("bytes"),                      Nullable] public long?     Bytes                { get; set; } // bigint
	}

	[Table(Schema="dbo", Name="Transformations")]
	public partial class Transformation
	{
		[PrimaryKey, Identity   ] public int       ID           { get; set; } // int
		[Column,     NotNull    ] public int       RootOperType { get; set; } // int
		[Column,     NotNull    ] public int       RootAcct     { get; set; } // int
		[Column,     NotNull    ] public int       FromOperType { get; set; } // int
		[Column,     NotNull    ] public int       FromAcct     { get; set; } // int
		[Column,     NotNull    ] public int       ToOperType   { get; set; } // int
		[Column,     NotNull    ] public int       ToAcct       { get; set; } // int
		[Column,     NotNull    ] public int       UserID       { get; set; } // int
		[Column,        Nullable] public DateTime? UserRealTime { get; set; } // datetime
	}

	[Table(Schema="dbo", Name="Users")]
	public partial class User
	{
		[PrimaryKey, Identity] public int    ID         { get; set; } // int
		[Column,     Nullable] public string Code       { get; set; } // nvarchar(255)
		[Column,     Nullable] public string Name       { get; set; } // nvarchar(255)
		[Column,     Nullable] public string Name2      { get; set; } // nvarchar(255)
		[Column,     Nullable] public int?   IsVeryUsed { get; set; } // int
		[Column,     Nullable] public int?   GroupID    { get; set; } // int
		[Column,     Nullable] public string Password   { get; set; } // nvarchar(50)
		[Column,     Nullable] public int?   UserLevel  { get; set; } // int
		[Column,     Nullable] public int?   Deleted    { get; set; } // int
		[Column,     Nullable] public string CardNumber { get; set; } // nvarchar(255)
	}

	[Table(Schema="dbo", Name="UsersGroups")]
	public partial class UsersGroup
	{
		[PrimaryKey, Identity] public int    ID   { get; set; } // int
		[Column,     Nullable] public string Code { get; set; } // nvarchar(255)
		[Column,     Nullable] public string Name { get; set; } // nvarchar(255)
	}

	[Table(Schema="dbo", Name="UsersSecurity")]
	public partial class UsersSecurity
	{
		[PrimaryKey, Identity] public int    ID          { get; set; } // int
		[Column,     Nullable] public int?   UserID      { get; set; } // int
		[Column,     Nullable] public string ControlName { get; set; } // nvarchar(100)
		[Column,     Nullable] public int?   State       { get; set; } // int
	}

	[Table(Schema="dbo", Name="VATGroups")]
	public partial class VATGroup
	{
		[PrimaryKey, Identity] public int     ID       { get; set; } // int
		[Column,     Nullable] public string  Code     { get; set; } // nvarchar(255)
		[Column,     Nullable] public string  Name     { get; set; } // nvarchar(255)
		[Column,     Nullable] public double? VATValue { get; set; } // float
	}

	public static partial class TableExtensions
	{
		public static ApplicationLog Find(this ITable<ApplicationLog> table, int ID)
		{
			return table.FirstOrDefault(t =>
				t.ID == ID);
		}

		public static CashBook Find(this ITable<CashBook> table, int ID)
		{
			return table.FirstOrDefault(t =>
				t.ID == ID);
		}

		public static Configuration Find(this ITable<Configuration> table, int ID)
		{
			return table.FirstOrDefault(t =>
				t.ID == ID);
		}

		public static CurrenciesHistory Find(this ITable<CurrenciesHistory> table, int ID)
		{
			return table.FirstOrDefault(t =>
				t.ID == ID);
		}

		public static Currency Find(this ITable<Currency> table, int ID)
		{
			return table.FirstOrDefault(t =>
				t.ID == ID);
		}

		public static Document Find(this ITable<Document> table, int ID)
		{
			return table.FirstOrDefault(t =>
				t.ID == ID);
		}

		public static ECRReceipt Find(this ITable<ECRReceipt> table, int ID)
		{
			return table.FirstOrDefault(t =>
				t.ID == ID);
		}

		public static Good Find(this ITable<Good> table, int ID)
		{
			return table.FirstOrDefault(t =>
				t.ID == ID);
		}

		public static GoodsGroup Find(this ITable<GoodsGroup> table, int ID)
		{
			return table.FirstOrDefault(t =>
				t.ID == ID);
		}

		public static InternalLog Find(this ITable<InternalLog> table, int ID)
		{
			return table.FirstOrDefault(t =>
				t.ID == ID);
		}

		public static Lot Find(this ITable<Lot> table, int ID)
		{
			return table.FirstOrDefault(t =>
				t.ID == ID);
		}

		public static Network Find(this ITable<Network> table, int Num)
		{
			return table.FirstOrDefault(t =>
				t.Num == Num);
		}

		public static NextAcct Find(this ITable<NextAcct> table, string NextAcctColumn)
		{
			return table.FirstOrDefault(t =>
				t.NextAcctColumn == NextAcctColumn);
		}

		public static Object Find(this ITable<Object> table, int ID)
		{
			return table.FirstOrDefault(t =>
				t.ID == ID);
		}

		public static ObjectsGroup Find(this ITable<ObjectsGroup> table, int ID)
		{
			return table.FirstOrDefault(t =>
				t.ID == ID);
		}

		public static Operation Find(this ITable<Operation> table, int ID)
		{
			return table.FirstOrDefault(t =>
				t.ID == ID);
		}

		public static OperationType Find(this ITable<OperationType> table, int ID)
		{
			return table.FirstOrDefault(t =>
				t.ID == ID);
		}

		public static Partner Find(this ITable<Partner> table, int ID)
		{
			return table.FirstOrDefault(t =>
				t.ID == ID);
		}

		public static PartnersGroup Find(this ITable<PartnersGroup> table, int ID)
		{
			return table.FirstOrDefault(t =>
				t.ID == ID);
		}

		public static Payment Find(this ITable<Payment> table, int ID)
		{
			return table.FirstOrDefault(t =>
				t.ID == ID);
		}

		public static PaymentType Find(this ITable<PaymentType> table, int ID)
		{
			return table.FirstOrDefault(t =>
				t.ID == ID);
		}

		public static PriceRule Find(this ITable<PriceRule> table, int ID)
		{
			return table.FirstOrDefault(t =>
				t.ID == ID);
		}

		public static Registration Find(this ITable<Registration> table, int ID)
		{
			return table.FirstOrDefault(t =>
				t.ID == ID);
		}

		public static SecurityEvent Find(this ITable<SecurityEvent> table, int ID)
		{
			return table.FirstOrDefault(t =>
				t.ID == ID);
		}

		public static Store Find(this ITable<Store> table, int ID)
		{
			return table.FirstOrDefault(t =>
				t.ID == ID);
		}

		public static System Find(this ITable<System> table, string Version)
		{
			return table.FirstOrDefault(t =>
				t.Version == Version);
		}

		public static Transformation Find(this ITable<Transformation> table, int ID)
		{
			return table.FirstOrDefault(t =>
				t.ID == ID);
		}

		public static User Find(this ITable<User> table, int ID)
		{
			return table.FirstOrDefault(t =>
				t.ID == ID);
		}

		public static UsersGroup Find(this ITable<UsersGroup> table, int ID)
		{
			return table.FirstOrDefault(t =>
				t.ID == ID);
		}

		public static UsersSecurity Find(this ITable<UsersSecurity> table, int ID)
		{
			return table.FirstOrDefault(t =>
				t.ID == ID);
		}

		public static VATGroup Find(this ITable<VATGroup> table, int ID)
		{
			return table.FirstOrDefault(t =>
				t.ID == ID);
		}
	}
}

#pragma warning restore 1591
