version: 2
jobs:
    build:
        docker:
            - image: circleci/ruby:2.4.1
    steps:
        - checkout
        - run: echo "A first green"
workflows:
    version: 2
    build:
        jobs:
            - build