export const OPERATIONS_REQUEST = 'OPERATIONS_REQUEST'
export const OPERATIONS_REQUEST_MORE = 'OPERATIONS_REQUEST_MORE'
export const OPERATIONS_SUCCESS = 'OPERATIONS_SUCCESS'
export const OPERATIONS_ERROR = 'OPERATIONS_ERROR'